// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiHandler } from 'next'
import { resend } from '../../lib/resend'

function sendReceipt(email: string, name: string) {
  return resend.emails.send({
    replyTo: process.env.EMAIL!,
    from: 'al@halyard.studio',
    to: email,
    text: `Hi ${name},\n\nThanks for reaching out. I'll in touch as soon as possible!\n\nCheers, Alex.\n\nThis email was autogenerated via Halyard API.`,
    subject: 'Halyard Enquiry',
  })
}

function forwardEmail(email: string, name: string, description: string) {
  return resend.emails.send({
    replyTo: email,
    from: 'al@halyard.studio',
    to: process.env.EMAIL!,
    text: `${description}.\n\nThis email was autogenerated via Halyard API.`,
    subject: `Halyard Enquiry from ${name}`,
  })
}

const handler: NextApiHandler = async (req, res) => {
  const { email, description, name } = JSON.parse(req.body)

  try {
    await Promise.all([
      sendReceipt(email, name),
      forwardEmail(email, name, description),
    ])
    console.log('Emails sent')
    res.status(200).json(req.body)
  } catch (error) {
    console.error(error)
    res.status(500)
  }
}

export default handler
